# Generated by Django 4.2.9 on 2024-01-10 21:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='admin firstname')),
                ('surname', models.CharField(max_length=100, verbose_name='admin surname')),
                ('admin_qualification', models.CharField(max_length=100, verbose_name='qualification')),
                ('email_address', models.EmailField(max_length=254)),
                ('contact_number', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Department Admin',
                'verbose_name_plural': 'Department Admins',
            },
        ),
        migrations.CreateModel(
            name='DrugsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.CharField(max_length=100, verbose_name='drug name')),
                ('date_created', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='date created')),
                ('date_supplied', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='date supplied')),
                ('date_manufactured', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='date manufactured')),
                ('date_expired', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='date expired')),
                ('drug_prescription', models.CharField(max_length=100, verbose_name='drug prescription')),
            ],
            options={
                'verbose_name': 'Drug',
                'verbose_name_plural': 'Drugs',
            },
        ),
        migrations.CreateModel(
            name='SymptomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=100, verbose_name='symptom')),
                ('date_created', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='date created')),
                ('doctor_assigned', models.ManyToManyField(max_length=100, related_name='doctor_assigned', to='accounts.doctor')),
                ('prescribed_drugs', models.ManyToManyField(related_name='prescribe_drug', to='PARTIENT_DOCTOR_MATCHING.drugsdetails')),
            ],
            options={
                'verbose_name': 'Symptom',
                'verbose_name_plural': 'Symptoms',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100, verbose_name='disease')),
                ('causative_agent', models.CharField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), max_length=100, null=True, verbose_name='causative agent')),
                ('date_created', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='date created')),
                ('doctor_assigned', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assigned_to_disease', to='accounts.doctor')),
                ('prescribed_drugs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_prescribe_drug', to='PARTIENT_DOCTOR_MATCHING.drugsdetails')),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, verbose_name='department')),
                ('date_created', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='date created')),
                ('department_admin', models.OneToOneField(blank=True, max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='department_admin', to='PARTIENT_DOCTOR_MATCHING.departmentadmin')),
                ('diseases', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='department_diseases', to='PARTIENT_DOCTOR_MATCHING.disease')),
                ('doctor_assigned', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='doctors_assigned_to_department', to='accounts.doctor')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
    ]
