# Generated by Django 4.2.9 on 2024-01-11 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PARTIENT_DOCTOR_MATCHING', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.ForeignKey(default=0, max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='disease_symptoms', to='PARTIENT_DOCTOR_MATCHING.symptomdetails'),
            preserve_default=False,
        ),
    ]
